import type { Metadata } from "next";
import { Krona_One } from "next/font/google";
import "./globals.css";
import Header from "./components/header"
import Footer from "./components/footer";

const kronaOne = Krona_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-krona-one",
  display: "swap",
});

export const metadata: Metadata = {
  title: "BGDPS Demon List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${kronaOne.variable} bg-main-bg`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
